# Generated by Django 3.1.1 on 2020-09-25 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('date_blacklisted', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EbayUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First name', models.CharField(blank=True, max_length=20)),
                ('Last name', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('street', models.CharField(max_length=20)),
                ('plz', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=20)),
                ('date_acquired', models.DateTimeField(auto_now=True)),
                ('date_sent', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('sent', models.BooleanField(default=False)),
                ('blacklisted', models.BooleanField(default=False)),
            ],
        ),
    ]
