# Generated by Django 3.1.1 on 2020-09-25 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebayuser',
            name='city',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='ebayuser',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='ebayuser',
            name='plz',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='ebayuser',
            name='street',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
