# Generated by Django 3.1.1 on 2020-09-27 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_ebayuser_cleaned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ebayuser',
            old_name='First name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='ebayuser',
            old_name='Last name',
            new_name='last_name',
        ),
    ]
