# Generated by Django 3.1.1 on 2020-09-30 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_auto_20200930_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebayuser',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
