# Generated by Django 3.1.1 on 2020-09-30 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_ebayuser_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebayuser',
            name='description',
            field=models.CharField(blank=True, max_length=3333),
        ),
    ]
