# Generated by Django 3.1.1 on 2020-10-02 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_auto_20200930_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebayuser',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
