# Generated by Django 3.1.1 on 2020-10-02 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_ebayuser_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebayuser',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
