# Generated by Django 3.1.1 on 2020-10-12 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_auto_20201002_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebayuser',
            name='date_cleaned',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
